name: hello-world
on: push
jobs:
  my-job:
    runs-on: ubuntu-latest
    container: gradle:6-jdk11

    steps:
      - name: Clone-down
        uses: actions/checkout@v3
      - name: Build-Application  
        run: ci/build-app.sh 
      - name: min-unit-test
        run: chmod +x ci/unit-test-app.sh && ci/unit-test-app.sh